### ISSUE TITLE
List secrets does not work

### ISSUE THREAD

**Issue by pijalu** [Nike-Inc/cerberus-go-client#14]
Listing secret of an SDB does not work: It returns a 404 instead of the expected list of secret

The issue is that this go-client uses Vault client under the hood to call the /v1/secret/{secret_path} API.
The Vault client uses stdlib path.Join to create the actual request PATH, but path.Join will drop any ending '/' if a path exists. 
* Vault code: https://github.com/hashicorp/vault/blob/master/api/client.go#L574 - 
* path.Join example: https://play.golang.org/p/-hhADEaiFix

This triggers an issue with Cerberus back-end that enforce/expect a trailing slash to path, and therefor returns 404.

Note:
I am not sure this is a bug in the client or in the backend:
I don't know why Cerberus enforces the trailing slash policy (https://github.com/Nike-Inc/cerberus-management-service/blob/master/src/main/java/com/nike/cerberus/SecureDataRequestService.java#L88) as it seems to lead to some additional handling (eg: https://github.com/Nike-Inc/cerberus-management-service/blob/master/src/main/java/com/nike/cerberus/service/SecureDataService.java#L289) and introduces unnatural/weird path resolution.

**Comment by mayitbeegh** [comment]
Should be fixed now
