### ISSUE TITLE
multi factor auth

### ISSUE THREAD

**Issue by basmoorkens** [Nike-Inc/cerberus-go-client#16]
Is there any way to use multifactor auth in the api?

**Comment by fieldju** [comment]
The Cerberus rest API supports MFA, this client does not support MFA.

**Comment by fieldju** [comment]
Just an update, we have this on our near term roadmap as there is a Golang CLI we are going to be open sourcing.

**Comment by fieldju** [comment]
I would like to see the client prompt for MFA but also support a `--mfa-code` flag for TOTP

**Comment by fieldju** [comment]
We removed user auth from the client for now in favor of using federated auth and gimme-aws-creds for user auth needs.
